# Generated by Django 3.2.16 on 2022-11-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PAIN', 'Pain'), ('FATIGUE', 'Fatigue')], max_length=100)),
                ('experienced_today', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('severity', models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0)),
                ('sleep', models.DecimalField(decimal_places=1, default=9, max_digits=3)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-time',),
            },
        ),
    ]
