# Generated by Django 4.1 on 2022-10-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('PAIN', 'Pain'), ('FATIGUE', 'Fatigue')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
