# Generated by Django 4.1 on 2022-10-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_post_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='experienced_today',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
    ]
