# Generated by Django 4.1 on 2022-10-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_post_experienced_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sleep',
            field=models.DecimalField(decimal_places=1, default=9, max_digits=3),
        ),
        migrations.AlterField(
            model_name='post',
            name='severity',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0),
        ),
    ]
